--- scripts/dtc/include-prefixes/arm64/broadcom/Makefile	2018-11-04 13:52:51.000000000 +0000
+++ scripts/dtc/include-prefixes/arm64/broadcom/Makefile	2021-04-01 22:04:54.399919520 +0100
@@ -1,8 +1,5 @@
 # SPDX-License-Identifier: GPL-2.0
 dtb-$(CONFIG_ARCH_BCM2835) += bcm2837-rpi-3-b.dtb
 
-dts-dirs	+= northstar2
-dts-dirs	+= stingray
-always		:= $(dtb-y)
-subdir-y	:= $(dts-dirs)
-clean-files	:= *.dtb
+subdir-y	+= northstar2
+subdir-y	+= stingray
